query list {
    gale {
        repo(name: "aweris/gale") {
            withWorkflowsDir(dir: "ci/workflows"){
                list(token: "$GITHUB_TOKEN")
            }
        }
    }
}

query run {
    gale {
        repo(name: "aweris/gale") {
            withWorkflowsDir(dir: "ci/workflows"){
                workflow(name: "ci/workflows/lint.yaml") {
                    withJob(name: "golangci-lint") {
                        withDebug{
                            run(token: "$GITHUB_TOKEN")
                        }
                    }
                }
            }
        }
    }
}