query list {
    gale {
        list (
            token: "$GITHUB_TOKEN",
            repo: "aweris/gale"
        )
    }
}

query run {
    gale {
        run(
            workflow: "ci/workflows/artifact-cache.yaml",
            token: "$GITHUB_TOKEN",
            repo: "aweris/gale",
            workflowsDir: "ci/workflows",
            debug: true
        )
    }
}