query list {
    gale {
        setToken(token: "$GITHUB_TOKEN") {
            repo(repo: "aweris/gale") {
               workflows(workflowsDir: "ci/workflows") {
                   list
               }
            }
        }
    }
}

query run_result {
    gale {
        setToken(token: "$GITHUB_TOKEN") {
            repo(repo: "aweris/gale") {
                workflows(workflowsDir: "ci/workflows") {
                    run(workflow: "step", job: "run") {
                        result
                    }
                }
            }
        }
    }
}

query run_export {
    gale {
        setToken(token: "$GITHUB_TOKEN") {
            repo(repo: "aweris/gale") {
                workflows(workflowsDir: "ci/workflows") {
                    run(workflow: "step", job: "run") {
                        directory(includeSource: true) {
                            export(path: ".gale")
                        }
                    }
                }
            }
        }
    }
}
