query list {
    gale {
        setToken(token: "$GITHUB_TOKEN") {
            repo(repo: "aweris/gale") {
               workflows(workflowsDir: "ci/workflows") {
                   list
               }
            }
        }
    }
}

query run_result {
    gale {
        setToken(token: "$GITHUB_TOKEN") {
            repo(repo: "aweris/gale") {
                workflows(workflowsDir: "ci/workflows") {
                    run(workflow: "outputs") {
                        directory {
                            export(path: ".gale")
                        }
                    }
                }
            }
        }
    }
}

query run_export {
    gale {
        setToken(token: "$GITHUB_TOKEN") {
            repo(repo: "kubernetes/minikube") {
                workflows {
                    run(workflow: "build", job: "build_minikube") {
                        directory(includeRepo: true, includeSecrets: true, includeEvent: true, includeActions: true, includeArtifacts: true) {
                            export(path: ".gale")
                        }
                    }
                }
            }
        }
    }
}
