name: publish

on:
  push:
    tags: ["**/v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Extract module name and version
        id: extract
        run: |
          echo "module=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT
          echo "version=$(echo $GITHUB_REF | cut -d / -f 4)" >> $GITHUB_OUTPUT

      - name: Fail if module name is empty
        run: |
          if [ -z "${{ steps.extract.outputs.module }}" ]; then
            echo "Module name is empty"
            exit 1
          fi

      - name: Fail if version is empty
        run: |
          if [ -z "${{ steps.extract.outputs.version }}" ]; then
            echo "Version is empty"
            exit 1
          fi

      - name: Publish module with tagged version
        uses: dagger/dagger-for-github@b6bf6af9f403e07eda5b4cd7a6dcd858fabfdc3d # v6.9.0
        with:
          workdir: ${{ steps.extract.outputs.module }}
          verb: publish
          version: "0.12.2"
